/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as BrandingRouteImport } from './routes/branding'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FirehacksRouteImport } from './routes/firehacks'
import { Route as JoinRouteImport } from './routes/join'
import { Route as MemberRouteImport } from './routes/member'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as SummerSignupRouteImport } from './routes/summer-signup'
import { Route as TeamRouteImport } from './routes/team'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminApplicationsRouteImport } from './routes/admin/applications'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AdminRequestsRouteImport } from './routes/admin/requests'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSetupRouteImport } from './routes/admin/setup'
import { Route as AdminTeamRouteImport } from './routes/admin/team'
import { Route as ApiSummerSignupsRouteImport } from './routes/api/summer-signups'
import { Route as ApiTeamRouteImport } from './routes/api/team'
import { Route as ApiVolunteersRouteImport } from './routes/api/volunteers'
import { Route as FirehacksIndexRouteImport } from './routes/firehacks.index'
import { Route as FirehacksMemberRouteImport } from './routes/firehacks.member'
import { Route as FirehacksPortalRouteImport } from './routes/firehacks.portal'
import { Route as MemberIndexRouteImport } from './routes/member.index'
import { Route as MemberLoginRouteImport } from './routes/member.login'
import { Route as MemberTasksRouteImport } from './routes/member.tasks'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as SummerSignupSlugRouteImport } from './routes/summer-signup.$slug'
import { Route as AdminAuthCallbackRouteImport } from './routes/admin/auth.callback'
import { Route as ApiAdminAuthVerifyRouteImport } from './routes/api/admin/auth-verify'
import { Route as ApiAdminDashboardStatsRouteImport } from './routes/api/admin/dashboard-stats'
import { Route as ApiAdminEmailConnectorRouteImport } from './routes/api/admin/email-connector'
import { Route as ApiAdminMembersRouteImport } from './routes/api/admin/members'
import { Route as ApiAdminRedeemInviteRouteImport } from './routes/api/admin/redeem-invite'
import { Route as ApiAdminSessionRouteImport } from './routes/api/admin/session'
import { Route as ApiAdminSummerSignupsRouteImport } from './routes/api/admin/summer-signups'
import { Route as ApiAdminTasksRouteImport } from './routes/api/admin/tasks'
import { Route as ApiAdminTeamsRouteImport } from './routes/api/admin/teams'
import { Route as ApiAdminVolunteersRouteImport } from './routes/api/admin/volunteers'
import { Route as ApiAdminWebsiteRequestsRouteImport } from './routes/api/admin/website-requests'
import { Route as ApiFirehacksWaiverRouteImport } from './routes/api/firehacks/waiver'
import { Route as ApiMemberTasksRouteImport } from './routes/api/member/tasks'
import { Route as FirehacksMemberLoginRouteImport } from './routes/firehacks.member.login'
import { Route as FirehacksPortalIndexRouteImport } from './routes/firehacks.portal.index'
import { Route as FirehacksPortalLoginRouteImport } from './routes/firehacks.portal.login'
import { Route as ApiAdminFirehacksProvisionMemberRouteImport } from './routes/api/admin/firehacks/provision-member'
import { Route as ApiAdminFirehacksProvisionPortalRouteImport } from './routes/api/admin/firehacks/provision-portal'
import { Route as ApiAdminFirehacksScanLookupRouteImport } from './routes/api/admin/firehacks/scan-lookup'
import { Route as ApiFirehacksMemberLookupRouteImport } from './routes/api/firehacks/member/lookup'
import { Route as ApiFirehacksMemberRedeemRouteImport } from './routes/api/firehacks/member/redeem'
import { Route as ApiFirehacksWaiverCompleteRouteImport } from './routes/api/firehacks/waiver.complete'
import { Route as ApiFirehacksWaiverPrepareRouteImport } from './routes/api/firehacks/waiver.prepare'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandingRoute = BrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FirehacksRoute = FirehacksRouteImport.update({
  id: '/firehacks',
  path: '/firehacks',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const SummerSignupRoute = SummerSignupRouteImport.update({
  id: '/summer-signup',
  path: '/summer-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiSummerSignupsRoute = ApiSummerSignupsRouteImport.update({
  id: '/api/summer-signups',
  path: '/api/summer-signups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamRoute = ApiTeamRouteImport.update({
  id: '/api/team',
  path: '/api/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVolunteersRoute = ApiVolunteersRouteImport.update({
  id: '/api/volunteers',
  path: '/api/volunteers',
  getParentRoute: () => rootRouteImport,
} as any)
const FirehacksIndexRoute = FirehacksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FirehacksRoute,
} as any)
const FirehacksMemberRoute = FirehacksMemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => FirehacksRoute,
} as any)
const FirehacksPortalRoute = FirehacksPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => FirehacksRoute,
} as any)
const MemberIndexRoute = MemberIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemberRoute,
} as any)
const MemberLoginRoute = MemberLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MemberRoute,
} as any)
const MemberTasksRoute = MemberTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => MemberRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const SummerSignupSlugRoute = SummerSignupSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SummerSignupRoute,
} as any)
const AdminAuthCallbackRoute = AdminAuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAdminAuthVerifyRoute = ApiAdminAuthVerifyRouteImport.update({
  id: '/api/admin/auth-verify',
  path: '/api/admin/auth-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDashboardStatsRoute = ApiAdminDashboardStatsRouteImport.update({
  id: '/api/admin/dashboard-stats',
  path: '/api/admin/dashboard-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminEmailConnectorRoute = ApiAdminEmailConnectorRouteImport.update({
  id: '/api/admin/email-connector',
  path: '/api/admin/email-connector',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMembersRoute = ApiAdminMembersRouteImport.update({
  id: '/api/admin/members',
  path: '/api/admin/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRedeemInviteRoute = ApiAdminRedeemInviteRouteImport.update({
  id: '/api/admin/redeem-invite',
  path: '/api/admin/redeem-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSessionRoute = ApiAdminSessionRouteImport.update({
  id: '/api/admin/session',
  path: '/api/admin/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSummerSignupsRoute = ApiAdminSummerSignupsRouteImport.update({
  id: '/api/admin/summer-signups',
  path: '/api/admin/summer-signups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTasksRoute = ApiAdminTasksRouteImport.update({
  id: '/api/admin/tasks',
  path: '/api/admin/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTeamsRoute = ApiAdminTeamsRouteImport.update({
  id: '/api/admin/teams',
  path: '/api/admin/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminVolunteersRoute = ApiAdminVolunteersRouteImport.update({
  id: '/api/admin/volunteers',
  path: '/api/admin/volunteers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminWebsiteRequestsRoute = ApiAdminWebsiteRequestsRouteImport.update({
  id: '/api/admin/website-requests',
  path: '/api/admin/website-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFirehacksWaiverRoute = ApiFirehacksWaiverRouteImport.update({
  id: '/api/firehacks/waiver',
  path: '/api/firehacks/waiver',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemberTasksRoute = ApiMemberTasksRouteImport.update({
  id: '/api/member/tasks',
  path: '/api/member/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const FirehacksMemberLoginRoute = FirehacksMemberLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => FirehacksMemberRoute,
} as any)
const FirehacksPortalIndexRoute = FirehacksPortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FirehacksPortalRoute,
} as any)
const FirehacksPortalLoginRoute = FirehacksPortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => FirehacksPortalRoute,
} as any)
const ApiAdminFirehacksProvisionMemberRoute =
  ApiAdminFirehacksProvisionMemberRouteImport.update({
    id: '/api/admin/firehacks/provision-member',
    path: '/api/admin/firehacks/provision-member',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminFirehacksProvisionPortalRoute =
  ApiAdminFirehacksProvisionPortalRouteImport.update({
    id: '/api/admin/firehacks/provision-portal',
    path: '/api/admin/firehacks/provision-portal',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminFirehacksScanLookupRoute =
  ApiAdminFirehacksScanLookupRouteImport.update({
    id: '/api/admin/firehacks/scan-lookup',
    path: '/api/admin/firehacks/scan-lookup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFirehacksMemberLookupRoute =
  ApiFirehacksMemberLookupRouteImport.update({
    id: '/api/firehacks/member/lookup',
    path: '/api/firehacks/member/lookup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFirehacksMemberRedeemRoute =
  ApiFirehacksMemberRedeemRouteImport.update({
    id: '/api/firehacks/member/redeem',
    path: '/api/firehacks/member/redeem',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFirehacksWaiverCompleteRoute =
  ApiFirehacksWaiverCompleteRouteImport.update({
    id: '/complete',
    path: '/complete',
    getParentRoute: () => ApiFirehacksWaiverRoute,
  } as any)
const ApiFirehacksWaiverPrepareRoute =
  ApiFirehacksWaiverPrepareRouteImport.update({
    id: '/prepare',
    path: '/prepare',
    getParentRoute: () => ApiFirehacksWaiverRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/branding': typeof BrandingRoute
  '/events': typeof EventsRoute
  '/firehacks': typeof FirehacksRouteWithChildren
  '/join': typeof JoinRoute
  '/member': typeof MemberRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/summer-signup': typeof SummerSignupRouteWithChildren
  '/team': typeof TeamRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/team': typeof AdminTeamRoute
  '/api/summer-signups': typeof ApiSummerSignupsRoute
  '/api/team': typeof ApiTeamRoute
  '/api/volunteers': typeof ApiVolunteersRoute
  '/firehacks/member': typeof FirehacksMemberRouteWithChildren
  '/firehacks/portal': typeof FirehacksPortalRouteWithChildren
  '/member/login': typeof MemberLoginRoute
  '/member/tasks': typeof MemberTasksRoute
  '/portal/login': typeof PortalLoginRoute
  '/summer-signup/$slug': typeof SummerSignupSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/firehacks/': typeof FirehacksIndexRoute
  '/member/': typeof MemberIndexRoute
  '/admin/auth/callback': typeof AdminAuthCallbackRoute
  '/api/admin/auth-verify': typeof ApiAdminAuthVerifyRoute
  '/api/admin/dashboard-stats': typeof ApiAdminDashboardStatsRoute
  '/api/admin/email-connector': typeof ApiAdminEmailConnectorRoute
  '/api/admin/members': typeof ApiAdminMembersRoute
  '/api/admin/redeem-invite': typeof ApiAdminRedeemInviteRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/admin/summer-signups': typeof ApiAdminSummerSignupsRoute
  '/api/admin/tasks': typeof ApiAdminTasksRoute
  '/api/admin/teams': typeof ApiAdminTeamsRoute
  '/api/admin/volunteers': typeof ApiAdminVolunteersRoute
  '/api/admin/website-requests': typeof ApiAdminWebsiteRequestsRoute
  '/api/firehacks/waiver': typeof ApiFirehacksWaiverRouteWithChildren
  '/api/member/tasks': typeof ApiMemberTasksRoute
  '/firehacks/member/login': typeof FirehacksMemberLoginRoute
  '/firehacks/portal/login': typeof FirehacksPortalLoginRoute
  '/firehacks/portal/': typeof FirehacksPortalIndexRoute
  '/api/admin/firehacks/provision-member': typeof ApiAdminFirehacksProvisionMemberRoute
  '/api/admin/firehacks/provision-portal': typeof ApiAdminFirehacksProvisionPortalRoute
  '/api/admin/firehacks/scan-lookup': typeof ApiAdminFirehacksScanLookupRoute
  '/api/firehacks/member/lookup': typeof ApiFirehacksMemberLookupRoute
  '/api/firehacks/member/redeem': typeof ApiFirehacksMemberRedeemRoute
  '/api/firehacks/waiver/complete': typeof ApiFirehacksWaiverCompleteRoute
  '/api/firehacks/waiver/prepare': typeof ApiFirehacksWaiverPrepareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/branding': typeof BrandingRoute
  '/events': typeof EventsRoute
  '/join': typeof JoinRoute
  '/portal': typeof PortalRouteWithChildren
  '/summer-signup': typeof SummerSignupRouteWithChildren
  '/team': typeof TeamRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/team': typeof AdminTeamRoute
  '/api/summer-signups': typeof ApiSummerSignupsRoute
  '/api/team': typeof ApiTeamRoute
  '/api/volunteers': typeof ApiVolunteersRoute
  '/firehacks/member': typeof FirehacksMemberRouteWithChildren
  '/member/login': typeof MemberLoginRoute
  '/member/tasks': typeof MemberTasksRoute
  '/portal/login': typeof PortalLoginRoute
  '/summer-signup/$slug': typeof SummerSignupSlugRoute
  '/admin': typeof AdminIndexRoute
  '/firehacks': typeof FirehacksIndexRoute
  '/member': typeof MemberIndexRoute
  '/admin/auth/callback': typeof AdminAuthCallbackRoute
  '/api/admin/auth-verify': typeof ApiAdminAuthVerifyRoute
  '/api/admin/dashboard-stats': typeof ApiAdminDashboardStatsRoute
  '/api/admin/email-connector': typeof ApiAdminEmailConnectorRoute
  '/api/admin/members': typeof ApiAdminMembersRoute
  '/api/admin/redeem-invite': typeof ApiAdminRedeemInviteRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/admin/summer-signups': typeof ApiAdminSummerSignupsRoute
  '/api/admin/tasks': typeof ApiAdminTasksRoute
  '/api/admin/teams': typeof ApiAdminTeamsRoute
  '/api/admin/volunteers': typeof ApiAdminVolunteersRoute
  '/api/admin/website-requests': typeof ApiAdminWebsiteRequestsRoute
  '/api/firehacks/waiver': typeof ApiFirehacksWaiverRouteWithChildren
  '/api/member/tasks': typeof ApiMemberTasksRoute
  '/firehacks/member/login': typeof FirehacksMemberLoginRoute
  '/firehacks/portal/login': typeof FirehacksPortalLoginRoute
  '/firehacks/portal': typeof FirehacksPortalIndexRoute
  '/api/admin/firehacks/provision-member': typeof ApiAdminFirehacksProvisionMemberRoute
  '/api/admin/firehacks/provision-portal': typeof ApiAdminFirehacksProvisionPortalRoute
  '/api/admin/firehacks/scan-lookup': typeof ApiAdminFirehacksScanLookupRoute
  '/api/firehacks/member/lookup': typeof ApiFirehacksMemberLookupRoute
  '/api/firehacks/member/redeem': typeof ApiFirehacksMemberRedeemRoute
  '/api/firehacks/waiver/complete': typeof ApiFirehacksWaiverCompleteRoute
  '/api/firehacks/waiver/prepare': typeof ApiFirehacksWaiverPrepareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/branding': typeof BrandingRoute
  '/events': typeof EventsRoute
  '/firehacks': typeof FirehacksRouteWithChildren
  '/join': typeof JoinRoute
  '/member': typeof MemberRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/summer-signup': typeof SummerSignupRouteWithChildren
  '/team': typeof TeamRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/team': typeof AdminTeamRoute
  '/api/summer-signups': typeof ApiSummerSignupsRoute
  '/api/team': typeof ApiTeamRoute
  '/api/volunteers': typeof ApiVolunteersRoute
  '/firehacks/member': typeof FirehacksMemberRouteWithChildren
  '/firehacks/portal': typeof FirehacksPortalRouteWithChildren
  '/member/login': typeof MemberLoginRoute
  '/member/tasks': typeof MemberTasksRoute
  '/portal/login': typeof PortalLoginRoute
  '/summer-signup/$slug': typeof SummerSignupSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/firehacks/': typeof FirehacksIndexRoute
  '/member/': typeof MemberIndexRoute
  '/admin/auth/callback': typeof AdminAuthCallbackRoute
  '/api/admin/auth-verify': typeof ApiAdminAuthVerifyRoute
  '/api/admin/dashboard-stats': typeof ApiAdminDashboardStatsRoute
  '/api/admin/email-connector': typeof ApiAdminEmailConnectorRoute
  '/api/admin/members': typeof ApiAdminMembersRoute
  '/api/admin/redeem-invite': typeof ApiAdminRedeemInviteRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/admin/summer-signups': typeof ApiAdminSummerSignupsRoute
  '/api/admin/tasks': typeof ApiAdminTasksRoute
  '/api/admin/teams': typeof ApiAdminTeamsRoute
  '/api/admin/volunteers': typeof ApiAdminVolunteersRoute
  '/api/admin/website-requests': typeof ApiAdminWebsiteRequestsRoute
  '/api/firehacks/waiver': typeof ApiFirehacksWaiverRouteWithChildren
  '/api/member/tasks': typeof ApiMemberTasksRoute
  '/firehacks/member/login': typeof FirehacksMemberLoginRoute
  '/firehacks/portal/login': typeof FirehacksPortalLoginRoute
  '/firehacks/portal/': typeof FirehacksPortalIndexRoute
  '/api/admin/firehacks/provision-member': typeof ApiAdminFirehacksProvisionMemberRoute
  '/api/admin/firehacks/provision-portal': typeof ApiAdminFirehacksProvisionPortalRoute
  '/api/admin/firehacks/scan-lookup': typeof ApiAdminFirehacksScanLookupRoute
  '/api/firehacks/member/lookup': typeof ApiFirehacksMemberLookupRoute
  '/api/firehacks/member/redeem': typeof ApiFirehacksMemberRedeemRoute
  '/api/firehacks/waiver/complete': typeof ApiFirehacksWaiverCompleteRoute
  '/api/firehacks/waiver/prepare': typeof ApiFirehacksWaiverPrepareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/branding'
    | '/events'
    | '/firehacks'
    | '/join'
    | '/member'
    | '/portal'
    | '/summer-signup'
    | '/team'
    | '/admin/applications'
    | '/admin/login'
    | '/admin/members'
    | '/admin/requests'
    | '/admin/settings'
    | '/admin/setup'
    | '/admin/team'
    | '/api/summer-signups'
    | '/api/team'
    | '/api/volunteers'
    | '/firehacks/member'
    | '/firehacks/portal'
    | '/member/login'
    | '/member/tasks'
    | '/portal/login'
    | '/summer-signup/$slug'
    | '/admin/'
    | '/firehacks/'
    | '/member/'
    | '/admin/auth/callback'
    | '/api/admin/auth-verify'
    | '/api/admin/dashboard-stats'
    | '/api/admin/email-connector'
    | '/api/admin/members'
    | '/api/admin/redeem-invite'
    | '/api/admin/session'
    | '/api/admin/summer-signups'
    | '/api/admin/tasks'
    | '/api/admin/teams'
    | '/api/admin/volunteers'
    | '/api/admin/website-requests'
    | '/api/firehacks/waiver'
    | '/api/member/tasks'
    | '/firehacks/member/login'
    | '/firehacks/portal/login'
    | '/firehacks/portal/'
    | '/api/admin/firehacks/provision-member'
    | '/api/admin/firehacks/provision-portal'
    | '/api/admin/firehacks/scan-lookup'
    | '/api/firehacks/member/lookup'
    | '/api/firehacks/member/redeem'
    | '/api/firehacks/waiver/complete'
    | '/api/firehacks/waiver/prepare'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/branding'
    | '/events'
    | '/join'
    | '/portal'
    | '/summer-signup'
    | '/team'
    | '/admin/applications'
    | '/admin/login'
    | '/admin/members'
    | '/admin/requests'
    | '/admin/settings'
    | '/admin/setup'
    | '/admin/team'
    | '/api/summer-signups'
    | '/api/team'
    | '/api/volunteers'
    | '/firehacks/member'
    | '/member/login'
    | '/member/tasks'
    | '/portal/login'
    | '/summer-signup/$slug'
    | '/admin'
    | '/firehacks'
    | '/member'
    | '/admin/auth/callback'
    | '/api/admin/auth-verify'
    | '/api/admin/dashboard-stats'
    | '/api/admin/email-connector'
    | '/api/admin/members'
    | '/api/admin/redeem-invite'
    | '/api/admin/session'
    | '/api/admin/summer-signups'
    | '/api/admin/tasks'
    | '/api/admin/teams'
    | '/api/admin/volunteers'
    | '/api/admin/website-requests'
    | '/api/firehacks/waiver'
    | '/api/member/tasks'
    | '/firehacks/member/login'
    | '/firehacks/portal/login'
    | '/firehacks/portal'
    | '/api/admin/firehacks/provision-member'
    | '/api/admin/firehacks/provision-portal'
    | '/api/admin/firehacks/scan-lookup'
    | '/api/firehacks/member/lookup'
    | '/api/firehacks/member/redeem'
    | '/api/firehacks/waiver/complete'
    | '/api/firehacks/waiver/prepare'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/branding'
    | '/events'
    | '/firehacks'
    | '/join'
    | '/member'
    | '/portal'
    | '/summer-signup'
    | '/team'
    | '/admin/applications'
    | '/admin/login'
    | '/admin/members'
    | '/admin/requests'
    | '/admin/settings'
    | '/admin/setup'
    | '/admin/team'
    | '/api/summer-signups'
    | '/api/team'
    | '/api/volunteers'
    | '/firehacks/member'
    | '/firehacks/portal'
    | '/member/login'
    | '/member/tasks'
    | '/portal/login'
    | '/summer-signup/$slug'
    | '/admin/'
    | '/firehacks/'
    | '/member/'
    | '/admin/auth/callback'
    | '/api/admin/auth-verify'
    | '/api/admin/dashboard-stats'
    | '/api/admin/email-connector'
    | '/api/admin/members'
    | '/api/admin/redeem-invite'
    | '/api/admin/session'
    | '/api/admin/summer-signups'
    | '/api/admin/tasks'
    | '/api/admin/teams'
    | '/api/admin/volunteers'
    | '/api/admin/website-requests'
    | '/api/firehacks/waiver'
    | '/api/member/tasks'
    | '/firehacks/member/login'
    | '/firehacks/portal/login'
    | '/firehacks/portal/'
    | '/api/admin/firehacks/provision-member'
    | '/api/admin/firehacks/provision-portal'
    | '/api/admin/firehacks/scan-lookup'
    | '/api/firehacks/member/lookup'
    | '/api/firehacks/member/redeem'
    | '/api/firehacks/waiver/complete'
    | '/api/firehacks/waiver/prepare'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  BrandingRoute: typeof BrandingRoute
  EventsRoute: typeof EventsRoute
  FirehacksRoute: typeof FirehacksRouteWithChildren
  JoinRoute: typeof JoinRoute
  MemberRoute: typeof MemberRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  SummerSignupRoute: typeof SummerSignupRouteWithChildren
  TeamRoute: typeof TeamRoute
  ApiSummerSignupsRoute: typeof ApiSummerSignupsRoute
  ApiTeamRoute: typeof ApiTeamRoute
  ApiVolunteersRoute: typeof ApiVolunteersRoute
  ApiAdminAuthVerifyRoute: typeof ApiAdminAuthVerifyRoute
  ApiAdminDashboardStatsRoute: typeof ApiAdminDashboardStatsRoute
  ApiAdminEmailConnectorRoute: typeof ApiAdminEmailConnectorRoute
  ApiAdminMembersRoute: typeof ApiAdminMembersRoute
  ApiAdminRedeemInviteRoute: typeof ApiAdminRedeemInviteRoute
  ApiAdminSessionRoute: typeof ApiAdminSessionRoute
  ApiAdminSummerSignupsRoute: typeof ApiAdminSummerSignupsRoute
  ApiAdminTasksRoute: typeof ApiAdminTasksRoute
  ApiAdminTeamsRoute: typeof ApiAdminTeamsRoute
  ApiAdminVolunteersRoute: typeof ApiAdminVolunteersRoute
  ApiAdminWebsiteRequestsRoute: typeof ApiAdminWebsiteRequestsRoute
  ApiFirehacksWaiverRoute: typeof ApiFirehacksWaiverRouteWithChildren
  ApiMemberTasksRoute: typeof ApiMemberTasksRoute
  ApiAdminFirehacksProvisionMemberRoute: typeof ApiAdminFirehacksProvisionMemberRoute
  ApiAdminFirehacksProvisionPortalRoute: typeof ApiAdminFirehacksProvisionPortalRoute
  ApiAdminFirehacksScanLookupRoute: typeof ApiAdminFirehacksScanLookupRoute
  ApiFirehacksMemberLookupRoute: typeof ApiFirehacksMemberLookupRoute
  ApiFirehacksMemberRedeemRoute: typeof ApiFirehacksMemberRedeemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branding': {
      id: '/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof BrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firehacks': {
      id: '/firehacks'
      path: '/firehacks'
      fullPath: '/firehacks'
      preLoaderRoute: typeof FirehacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summer-signup': {
      id: '/summer-signup'
      path: '/summer-signup'
      fullPath: '/summer-signup'
      preLoaderRoute: typeof SummerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/summer-signups': {
      id: '/api/summer-signups'
      path: '/api/summer-signups'
      fullPath: '/api/summer-signups'
      preLoaderRoute: typeof ApiSummerSignupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team': {
      id: '/api/team'
      path: '/api/team'
      fullPath: '/api/team'
      preLoaderRoute: typeof ApiTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/volunteers': {
      id: '/api/volunteers'
      path: '/api/volunteers'
      fullPath: '/api/volunteers'
      preLoaderRoute: typeof ApiVolunteersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firehacks/': {
      id: '/firehacks/'
      path: '/'
      fullPath: '/firehacks/'
      preLoaderRoute: typeof FirehacksIndexRouteImport
      parentRoute: typeof FirehacksRoute
    }
    '/firehacks/member': {
      id: '/firehacks/member'
      path: '/member'
      fullPath: '/firehacks/member'
      preLoaderRoute: typeof FirehacksMemberRouteImport
      parentRoute: typeof FirehacksRoute
    }
    '/firehacks/portal': {
      id: '/firehacks/portal'
      path: '/portal'
      fullPath: '/firehacks/portal'
      preLoaderRoute: typeof FirehacksPortalRouteImport
      parentRoute: typeof FirehacksRoute
    }
    '/member/': {
      id: '/member/'
      path: '/'
      fullPath: '/member/'
      preLoaderRoute: typeof MemberIndexRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/login': {
      id: '/member/login'
      path: '/login'
      fullPath: '/member/login'
      preLoaderRoute: typeof MemberLoginRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/tasks': {
      id: '/member/tasks'
      path: '/tasks'
      fullPath: '/member/tasks'
      preLoaderRoute: typeof MemberTasksRouteImport
      parentRoute: typeof MemberRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/summer-signup/$slug': {
      id: '/summer-signup/$slug'
      path: '/$slug'
      fullPath: '/summer-signup/$slug'
      preLoaderRoute: typeof SummerSignupSlugRouteImport
      parentRoute: typeof SummerSignupRoute
    }
    '/admin/auth/callback': {
      id: '/admin/auth/callback'
      path: '/auth/callback'
      fullPath: '/admin/auth/callback'
      preLoaderRoute: typeof AdminAuthCallbackRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/admin/auth-verify': {
      id: '/api/admin/auth-verify'
      path: '/api/admin/auth-verify'
      fullPath: '/api/admin/auth-verify'
      preLoaderRoute: typeof ApiAdminAuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/dashboard-stats': {
      id: '/api/admin/dashboard-stats'
      path: '/api/admin/dashboard-stats'
      fullPath: '/api/admin/dashboard-stats'
      preLoaderRoute: typeof ApiAdminDashboardStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/email-connector': {
      id: '/api/admin/email-connector'
      path: '/api/admin/email-connector'
      fullPath: '/api/admin/email-connector'
      preLoaderRoute: typeof ApiAdminEmailConnectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/members': {
      id: '/api/admin/members'
      path: '/api/admin/members'
      fullPath: '/api/admin/members'
      preLoaderRoute: typeof ApiAdminMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/redeem-invite': {
      id: '/api/admin/redeem-invite'
      path: '/api/admin/redeem-invite'
      fullPath: '/api/admin/redeem-invite'
      preLoaderRoute: typeof ApiAdminRedeemInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/session': {
      id: '/api/admin/session'
      path: '/api/admin/session'
      fullPath: '/api/admin/session'
      preLoaderRoute: typeof ApiAdminSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/summer-signups': {
      id: '/api/admin/summer-signups'
      path: '/api/admin/summer-signups'
      fullPath: '/api/admin/summer-signups'
      preLoaderRoute: typeof ApiAdminSummerSignupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/tasks': {
      id: '/api/admin/tasks'
      path: '/api/admin/tasks'
      fullPath: '/api/admin/tasks'
      preLoaderRoute: typeof ApiAdminTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/teams': {
      id: '/api/admin/teams'
      path: '/api/admin/teams'
      fullPath: '/api/admin/teams'
      preLoaderRoute: typeof ApiAdminTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/volunteers': {
      id: '/api/admin/volunteers'
      path: '/api/admin/volunteers'
      fullPath: '/api/admin/volunteers'
      preLoaderRoute: typeof ApiAdminVolunteersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/website-requests': {
      id: '/api/admin/website-requests'
      path: '/api/admin/website-requests'
      fullPath: '/api/admin/website-requests'
      preLoaderRoute: typeof ApiAdminWebsiteRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/firehacks/waiver': {
      id: '/api/firehacks/waiver'
      path: '/api/firehacks/waiver'
      fullPath: '/api/firehacks/waiver'
      preLoaderRoute: typeof ApiFirehacksWaiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/member/tasks': {
      id: '/api/member/tasks'
      path: '/api/member/tasks'
      fullPath: '/api/member/tasks'
      preLoaderRoute: typeof ApiMemberTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firehacks/member/login': {
      id: '/firehacks/member/login'
      path: '/login'
      fullPath: '/firehacks/member/login'
      preLoaderRoute: typeof FirehacksMemberLoginRouteImport
      parentRoute: typeof FirehacksMemberRoute
    }
    '/firehacks/portal/': {
      id: '/firehacks/portal/'
      path: '/'
      fullPath: '/firehacks/portal/'
      preLoaderRoute: typeof FirehacksPortalIndexRouteImport
      parentRoute: typeof FirehacksPortalRoute
    }
    '/firehacks/portal/login': {
      id: '/firehacks/portal/login'
      path: '/login'
      fullPath: '/firehacks/portal/login'
      preLoaderRoute: typeof FirehacksPortalLoginRouteImport
      parentRoute: typeof FirehacksPortalRoute
    }
    '/api/admin/firehacks/provision-member': {
      id: '/api/admin/firehacks/provision-member'
      path: '/api/admin/firehacks/provision-member'
      fullPath: '/api/admin/firehacks/provision-member'
      preLoaderRoute: typeof ApiAdminFirehacksProvisionMemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/firehacks/provision-portal': {
      id: '/api/admin/firehacks/provision-portal'
      path: '/api/admin/firehacks/provision-portal'
      fullPath: '/api/admin/firehacks/provision-portal'
      preLoaderRoute: typeof ApiAdminFirehacksProvisionPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/firehacks/scan-lookup': {
      id: '/api/admin/firehacks/scan-lookup'
      path: '/api/admin/firehacks/scan-lookup'
      fullPath: '/api/admin/firehacks/scan-lookup'
      preLoaderRoute: typeof ApiAdminFirehacksScanLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/firehacks/member/lookup': {
      id: '/api/firehacks/member/lookup'
      path: '/api/firehacks/member/lookup'
      fullPath: '/api/firehacks/member/lookup'
      preLoaderRoute: typeof ApiFirehacksMemberLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/firehacks/member/redeem': {
      id: '/api/firehacks/member/redeem'
      path: '/api/firehacks/member/redeem'
      fullPath: '/api/firehacks/member/redeem'
      preLoaderRoute: typeof ApiFirehacksMemberRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/firehacks/waiver/complete': {
      id: '/api/firehacks/waiver/complete'
      path: '/complete'
      fullPath: '/api/firehacks/waiver/complete'
      preLoaderRoute: typeof ApiFirehacksWaiverCompleteRouteImport
      parentRoute: typeof ApiFirehacksWaiverRoute
    }
    '/api/firehacks/waiver/prepare': {
      id: '/api/firehacks/waiver/prepare'
      path: '/prepare'
      fullPath: '/api/firehacks/waiver/prepare'
      preLoaderRoute: typeof ApiFirehacksWaiverPrepareRouteImport
      parentRoute: typeof ApiFirehacksWaiverRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAuthCallbackRoute: typeof AdminAuthCallbackRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSetupRoute: AdminSetupRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAuthCallbackRoute: AdminAuthCallbackRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface FirehacksMemberRouteChildren {
  FirehacksMemberLoginRoute: typeof FirehacksMemberLoginRoute
}

const FirehacksMemberRouteChildren: FirehacksMemberRouteChildren = {
  FirehacksMemberLoginRoute: FirehacksMemberLoginRoute,
}

const FirehacksMemberRouteWithChildren = FirehacksMemberRoute._addFileChildren(
  FirehacksMemberRouteChildren,
)

interface FirehacksPortalRouteChildren {
  FirehacksPortalLoginRoute: typeof FirehacksPortalLoginRoute
  FirehacksPortalIndexRoute: typeof FirehacksPortalIndexRoute
}

const FirehacksPortalRouteChildren: FirehacksPortalRouteChildren = {
  FirehacksPortalLoginRoute: FirehacksPortalLoginRoute,
  FirehacksPortalIndexRoute: FirehacksPortalIndexRoute,
}

const FirehacksPortalRouteWithChildren = FirehacksPortalRoute._addFileChildren(
  FirehacksPortalRouteChildren,
)

interface FirehacksRouteChildren {
  FirehacksMemberRoute: typeof FirehacksMemberRouteWithChildren
  FirehacksPortalRoute: typeof FirehacksPortalRouteWithChildren
  FirehacksIndexRoute: typeof FirehacksIndexRoute
}

const FirehacksRouteChildren: FirehacksRouteChildren = {
  FirehacksMemberRoute: FirehacksMemberRouteWithChildren,
  FirehacksPortalRoute: FirehacksPortalRouteWithChildren,
  FirehacksIndexRoute: FirehacksIndexRoute,
}

const FirehacksRouteWithChildren = FirehacksRoute._addFileChildren(
  FirehacksRouteChildren,
)

interface MemberRouteChildren {
  MemberLoginRoute: typeof MemberLoginRoute
  MemberTasksRoute: typeof MemberTasksRoute
  MemberIndexRoute: typeof MemberIndexRoute
}

const MemberRouteChildren: MemberRouteChildren = {
  MemberLoginRoute: MemberLoginRoute,
  MemberTasksRoute: MemberTasksRoute,
  MemberIndexRoute: MemberIndexRoute,
}

const MemberRouteWithChildren =
  MemberRoute._addFileChildren(MemberRouteChildren)

interface PortalRouteChildren {
  PortalLoginRoute: typeof PortalLoginRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalLoginRoute: PortalLoginRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface SummerSignupRouteChildren {
  SummerSignupSlugRoute: typeof SummerSignupSlugRoute
}

const SummerSignupRouteChildren: SummerSignupRouteChildren = {
  SummerSignupSlugRoute: SummerSignupSlugRoute,
}

const SummerSignupRouteWithChildren = SummerSignupRoute._addFileChildren(
  SummerSignupRouteChildren,
)

interface ApiFirehacksWaiverRouteChildren {
  ApiFirehacksWaiverCompleteRoute: typeof ApiFirehacksWaiverCompleteRoute
  ApiFirehacksWaiverPrepareRoute: typeof ApiFirehacksWaiverPrepareRoute
}

const ApiFirehacksWaiverRouteChildren: ApiFirehacksWaiverRouteChildren = {
  ApiFirehacksWaiverCompleteRoute: ApiFirehacksWaiverCompleteRoute,
  ApiFirehacksWaiverPrepareRoute: ApiFirehacksWaiverPrepareRoute,
}

const ApiFirehacksWaiverRouteWithChildren =
  ApiFirehacksWaiverRoute._addFileChildren(ApiFirehacksWaiverRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  BrandingRoute: BrandingRoute,
  EventsRoute: EventsRoute,
  FirehacksRoute: FirehacksRouteWithChildren,
  JoinRoute: JoinRoute,
  MemberRoute: MemberRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  SummerSignupRoute: SummerSignupRouteWithChildren,
  TeamRoute: TeamRoute,
  ApiSummerSignupsRoute: ApiSummerSignupsRoute,
  ApiTeamRoute: ApiTeamRoute,
  ApiVolunteersRoute: ApiVolunteersRoute,
  ApiAdminAuthVerifyRoute: ApiAdminAuthVerifyRoute,
  ApiAdminDashboardStatsRoute: ApiAdminDashboardStatsRoute,
  ApiAdminEmailConnectorRoute: ApiAdminEmailConnectorRoute,
  ApiAdminMembersRoute: ApiAdminMembersRoute,
  ApiAdminRedeemInviteRoute: ApiAdminRedeemInviteRoute,
  ApiAdminSessionRoute: ApiAdminSessionRoute,
  ApiAdminSummerSignupsRoute: ApiAdminSummerSignupsRoute,
  ApiAdminTasksRoute: ApiAdminTasksRoute,
  ApiAdminTeamsRoute: ApiAdminTeamsRoute,
  ApiAdminVolunteersRoute: ApiAdminVolunteersRoute,
  ApiAdminWebsiteRequestsRoute: ApiAdminWebsiteRequestsRoute,
  ApiFirehacksWaiverRoute: ApiFirehacksWaiverRouteWithChildren,
  ApiMemberTasksRoute: ApiMemberTasksRoute,
  ApiAdminFirehacksProvisionMemberRoute: ApiAdminFirehacksProvisionMemberRoute,
  ApiAdminFirehacksProvisionPortalRoute: ApiAdminFirehacksProvisionPortalRoute,
  ApiAdminFirehacksScanLookupRoute: ApiAdminFirehacksScanLookupRoute,
  ApiFirehacksMemberLookupRoute: ApiFirehacksMemberLookupRoute,
  ApiFirehacksMemberRedeemRoute: ApiFirehacksMemberRedeemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
